# Generated by Django 5.0.2 on 2024-04-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('surname', models.TextField(db_column='Surname')),
                ('mobile_number', models.IntegerField(db_column='Mobile Number')),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('password', models.CharField(db_column='Password', max_length=20)),
            ],
            options={
                'db_table': 'administrators',
                'managed': False,
            },
        ),
    ]
