# Generated by Django 5.0.2 on 2024-04-12 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('apptmnt_id', models.IntegerField(db_column='Apptmnt_ID', primary_key=True, serialize=False)),
                ('scheduled_on', models.DateField(db_column='Scheduled_On')),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
            ],
            options={
                'db_table': 'appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(db_column='Dept_ID', primary_key=True, serialize=False)),
                ('dept_head', models.CharField(db_column='Dept_Head', max_length=20)),
                ('dept_name', models.CharField(db_column='Dept_Name', max_length=15)),
                ('emp_count', models.IntegerField(blank=True, db_column='Emp_Count', null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diag_no', models.IntegerField(db_column='Diag_No', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('details', models.TextField(db_column='Details')),
                ('remark', models.TextField(db_column='Remark')),
                ('date', models.DateTimeField(db_column='Date')),
                ('doc_id', models.IntegerField(db_column='Doc_ID', unique=True)),
            ],
            options={
                'db_table': 'diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.IntegerField(db_column='Doc_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('surname', models.TextField(db_column='Surname')),
                ('mobile_number', models.IntegerField(db_column='Mobile Number')),
                ('department', models.TextField(db_column='Department')),
                ('status', models.TextField(db_column='Status')),
                ('address', models.CharField(db_column='Address', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=20)),
                ('password', models.CharField(db_column='Password', max_length=20)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('contact_id', models.IntegerField(db_column='Contact_ID', primary_key=True, serialize=False)),
                ('contact_name', models.CharField(db_column='Contact_Name', max_length=20)),
                ('phone', models.CharField(db_column='Phone', max_length=12)),
                ('relation', models.CharField(db_column='Relation', max_length=20)),
            ],
            options={
                'db_table': 'emergency_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_number', models.CharField(db_column='ID_Number', max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('surname', models.TextField(db_column='Surname')),
                ('address', models.CharField(db_column='Address', max_length=50)),
                ('mobile_number', models.IntegerField(db_column='Mobile Number')),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('password', models.CharField(db_column='Password', max_length=20)),
                ('age', models.IntegerField(db_column='Age')),
                ('gender', models.TextField(db_column='Gender')),
                ('insti_id', models.IntegerField(db_column='Insti_ID', unique=True)),
                ('description', models.TextField(db_column='Description')),
                ('status', models.TextField(db_column='Status')),
                ('admission_date', models.DateField(db_column='Admission_Date')),
                ('discharge_date', models.DateField(db_column='Discharge_Date')),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('policy_number', models.CharField(db_column='Policy_Number', max_length=20, primary_key=True, serialize=False)),
                ('ins_code', models.CharField(db_column='Ins_Code', max_length=20)),
                ('end_date', models.CharField(blank=True, db_column='End_Date', max_length=10, null=True)),
                ('provider', models.CharField(blank=True, db_column='Provider', max_length=20, null=True)),
                ('plan', models.CharField(blank=True, db_column='Plan', max_length=20, null=True)),
                ('coverage', models.CharField(blank=True, db_column='Coverage', max_length=20, null=True)),
                ('maternity', models.IntegerField(blank=True, db_column='Maternity', null=True)),
                ('dental', models.IntegerField(blank=True, db_column='Dental', null=True)),
                ('optical', models.IntegerField(blank=True, db_column='Optical', null=True)),
            ],
            options={
                'db_table': 'insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LabScreening',
            fields=[
                ('lab_id', models.IntegerField(db_column='Lab_ID', primary_key=True, serialize=False)),
                ('technician_id', models.IntegerField(db_column='Technician_ID')),
                ('test_cost', models.DecimalField(blank=True, db_column='Test_Cost', decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(db_column='Date')),
            ],
            options={
                'db_table': 'lab_screening',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('record_id', models.IntegerField(db_column='Record_ID', primary_key=True, serialize=False)),
                ('allergies', models.CharField(blank=True, db_column='Allergies', max_length=50, null=True)),
                ('pre_conditions', models.CharField(blank=True, db_column='Pre_Conditions', max_length=50, null=True)),
            ],
            options={
                'db_table': 'medical_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicinePayments',
            fields=[
                ('medpay_id', models.IntegerField(db_column='MedPay_ID', primary_key=True, serialize=False)),
                ('date_and_time', models.DateTimeField(db_column='Date and Time')),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'medicine payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('med_id', models.IntegerField(db_column='Med_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('price', models.IntegerField(db_column='Price')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('status', models.TextField(db_column='Status')),
            ],
            options={
                'db_table': 'medicines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.IntegerField(db_column='Nurse_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('surname', models.TextField(db_column='Surname')),
                ('mobile_number', models.IntegerField(db_column='Mobile Number')),
                ('email', models.TextField(db_column='Email')),
                ('address', models.CharField(db_column='Address', max_length=50)),
                ('status', models.TextField(db_column='Status')),
                ('department', models.TextField(db_column='Department')),
            ],
            options={
                'db_table': 'nurse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('receipt_number', models.IntegerField(db_column='Receipt Number', primary_key=True, serialize=False)),
                ('date_and_time', models.DateTimeField(db_column='Date and Time')),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('pharm_id', models.IntegerField(db_column='Pharm_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('surname', models.TextField(db_column='Surname')),
                ('mobile_number', models.IntegerField(db_column='Mobile Number')),
                ('address', models.CharField(db_column='Address', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=20)),
                ('password', models.IntegerField(db_column='Password')),
                ('insti_id', models.IntegerField(db_column='Insti_ID', unique=True)),
                ('status', models.TextField(db_column='Status')),
            ],
            options={
                'db_table': 'pharmacist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.IntegerField(db_column='Prescription_ID', primary_key=True, serialize=False)),
                ('date_field', models.DateField(blank=True, db_column='Date_', null=True)),
                ('dosage', models.IntegerField(blank=True, db_column='Dosage', null=True)),
            ],
            options={
                'db_table': 'prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('surname', models.TextField(db_column='Surname')),
                ('mobile_number', models.IntegerField(db_column='Mobile Number')),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('password', models.CharField(db_column='Password', max_length=20)),
            ],
            options={
                'db_table': 'receptionist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(db_column='Room_ID', primary_key=True, serialize=False)),
                ('room_type', models.CharField(db_column='Room_Type', max_length=50)),
                ('room_cost', models.DecimalField(blank=True, db_column='Room_Cost', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Administrators',
        ),
        migrations.CreateModel(
            name='HealthInstitution',
            fields=[
                ('insti', models.OneToOneField(db_column='Insti_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.patient')),
                ('name', models.TextField(db_column='Name')),
                ('type', models.TextField(db_column='Type')),
                ('location', models.CharField(db_column='Location', max_length=50)),
                ('status', models.TextField(db_column='Status')),
            ],
            options={
                'db_table': 'health institution',
                'managed': False,
            },
        ),
    ]
